# Generated by Django 3.0.8 on 2020-08-04 15:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExampleCss', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExampleCssModel',
            new_name='TestCss',
        ),
    ]
