# Generated by Django 3.0.8 on 2020-07-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodId', models.CharField(max_length=100)),
                ('FoodName', models.CharField(max_length=100)),
                ('MealTime', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('dinner', 'Dinner'), ('other', 'Any Other Time')], default=False, max_length=100)),
                ('Taste', models.CharField(choices=[('sweet', 'Sweet'), ('sour', 'Sour'), ('salt', 'Salt'), ('hot', 'Hot'), ('mixed', 'Mixed')], default=False, max_length=100)),
                ('MajorIngredient', models.CharField(max_length=200)),
                ('SpecialIngredient', models.CharField(max_length=500)),
            ],
        ),
    ]
