# Generated by Django 3.0.8 on 2020-07-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoordinatorId', models.CharField(max_length=100)),
                ('CoordinatorName', models.CharField(max_length=100)),
                ('Institute', models.CharField(choices=[('school', 'School'), ('ngo', 'NGO')], default=False, max_length=100)),
            ],
        ),
    ]
