# Generated by Django 3.0.8 on 2020-08-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Institute', models.CharField(choices=[('School', 'School'), ('NGO', 'NGO')], default='School', max_length=10)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=10)),
                ('Email', models.EmailField(max_length=100)),
                ('ContactNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
