# Generated by Django 3.0.8 on 2020-08-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherregistrationmodel',
            name='Password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
