# Generated by Django 3.0.8 on 2020-08-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherRegistration', '0002_teacherregistrationmodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
