# Generated by Django 3.0.8 on 2020-08-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationForm', '0002_auto_20200801_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerationformmodel',
            name='Hip',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
