# Generated by Django 3.0.8 on 2020-09-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietRecallAppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meal', models.CharField(choices=[('BreakFast', 'BreakFast'), ('Lunch', 'Lunch'), ('Evening Snacks', ' Evening Snacks'), ('Dinner', 'Dinner')], default='Breakfast', max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('EatDate', models.DateField()),
                ('EatTime', models.DateTimeField()),
            ],
        ),
    ]
