# Generated by Django 3.0.8 on 2020-08-11 09:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', multiselectfield.db.fields.MultiSelectField(choices=[('sleeping', 'Sleeping'), ('jumping', 'jumping')], default='False', max_length=16)),
            ],
        ),
    ]
