# Generated by Django 3.0.8 on 2020-07-31 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecipeName', models.CharField(max_length=100)),
                ('DishType', models.CharField(max_length=100)),
                ('CookingProcess', models.CharField(choices=[('sf', 'Shallo Fried'), ('df', 'Deep Fried'), ('bo', 'Boiled'), ('ba', 'Baked'), ('st', 'Steamed'), ('rs', 'Roasted'), ('ca', 'Canned'), ('bm', 'Bought From Market')], default=False, max_length=100)),
                ('ExplainDish', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
