# Generated by Django 3.0.8 on 2020-08-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeForm', '0002_auto_20200801_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='CookingProcess',
            field=models.CharField(choices=[('sf', 'Shallow Fried'), ('df', 'Deep Fried'), ('bo', 'Boiled'), ('ba', 'Baked'), ('st', 'Steamed'), ('rs', 'Roasted'), ('ca', 'Canned'), ('bm', 'Bought From Market')], default=False, max_length=100),
        ),
    ]
