# Generated by Django 3.0.8 on 2020-09-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeForm', '0004_auto_20200925_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='CookingProcess',
            field=models.CharField(choices=[('sf', 'Shallow Fried'), ('df', 'Deep Fried'), ('bo', 'Boiled'), ('ba', 'Baked'), ('st', 'Steamed'), ('rs', 'Roasted'), ('ca', 'Canned'), ('bm', 'Bought From Market')], default='Shallow Fried', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='DishType',
            field=models.CharField(choices=[('maincourse', 'Main Course'), ('snacks', 'Snacks')], default='Snacks', max_length=100),
        ),
    ]
